### ISSUE TITLE
Idea: Case study Open Source Launch "Toolkit Bestandeskarte - TBk"

### ISSUE THREAD

**Issue by Hannes-Ole** [bfh/open-source#47]
## Funnel Entry Date
`2023-01`

## Idea Owner
@Hannes-Ole 

## Idea Description
Use an on-going project of the Waldwissenschaftliches Institut (WWI) as a case study to identify and apply the potential of the Open Source Digital Knowledge connection (exchange, expertise, knowledge, community of practice...).

For `OS Digital Knowledge Core group`
who `participate in this project`
the `Open Source Launch "Toolkit Bestandeskarte - TBk"`
is a `case study`
that `provides insights into what questions arise (from an "amateur" point of view) in the process of launching a new Open Source project from scratch`
unlike `a mere theoretical collection of knowledge about Open Source`
our solution `gives a practical example, what information is relevant "for beginners" and people searching help and knowledge in Open Source topics`

## Business Outcomes

`<The measurable benefits that the business can anticipate if the idea hypothesis is proven to be correct.>`
- a **practical** example the Community of Practice #44 can practice on
- knowledge that was used/generated in the process and can be published as such on the Open Source Knowledge Platform = OSKP (#45)
- a case study that serves as an example scenario for applicable contents on the OSKP (#45)
- a successfully implemented, well advised Open Source launch

## Leading Indicators

`<The early measures that will help predict the business outcome hypothesis.>`
- there are knowledgeable people interested
- the Open Source launch progresses
- OS knowledge is required/used/generated

## Nonfunctional Requirements (NFRs) e.g. via [ISO-25010](https://www.inztitut.de/blog/glossar/iso-25010/)

`<Nonfunctional requirements (NFRs) associated with the idea.>`
- the project is ready to launch
- it is suited for a practical example

--
derived from [SAFe Epic Hypothesis Statement Template](https://www.scaledagileframework.com/epic/)

**Comment by Hannes-Ole** [comment]
**Tasks**: 
- Datum für OpenSource Launch mit Christian Rosset besprechen
- OpenSource Veröffentlichung
- Homepage für Projekt
- Outline stattgefundener (und potenzieller) Support durch OSDK-community 
    + bisheriger Support durch IPST, Matthias Stürmer/Amir Sahi
    + Support durch OSDK-community (wingman @MarkusTiede): Offene Fragestellungen, z.B. BFH-Kompatibilität
- Artikel / Story die 

Optional:
- [waldmonitoring.ch](https://waldmonitoring.ch/) als mögliche zweite Story/Begleitstory (ist bereits ein OpenSource Projekt, das ohne grossen Support/Community veröffentlicht wurde, aber im selben Kontext lebt wie TBk)

**Comment by MarkusTiede** [comment]
- [ ] hat unsere Community einen Namen - wenn ja welchen
  - [ ] OSDK-community?

**Comment by Hannes-Ole** [comment]
Im heutigem Treffen haben wir beschlossen uns an dem "Open Source Project Creation Overview" der TODO Group zu orientieren. Der Fall "TBk Case Study" wird eine Instanz der dort skizzierten Guidelines, vermutlich an einigen Stellen auf pragmatische Abkürzungen reduziert (die wir dann ggf. begründen).

- [ ] Instanziieren des [TODO Group "OS Project creation templates"](https://nextcloud.bfh.science/index.php/apps/files/?dir=/TBk/TBk_Konzept_BAFU&fileid=25688147)
   - [ ] Bisherige Arbeiten/Erkenntnisse anhand dieses templates zusammenfassen @Hannes-Ole, ggf. auch mit Unterstützung @MarkusTiede 
   - [ ] Tasks für die "ausstehenden" Checklist-Items erstellen
   - [ ] "Challenge Checklist" - wo gehen wir eigene Wege?

**Comment by Hannes-Ole** [comment]
Kurzes Update Projektstand:
- 26.04.2023 : Meeting Dachprojektskizzierung (Christian Rosset/Hannes Horneber); nächster grosser Schritt für die Formalisierung der TBk-Community ("Begleitgruppe/Kerngruppe TBk" ... Name wird noch festgelegt). Danach: Formierung der TBk Kerngruppe und erstes Konstituierendes Treffen planen.
- ab 01.05.2023 : On-Boarding neuer Mitarbeiter (Entwickler, Peter Thür) ab Anfang Mai, eventuell sogar eine weitere Person. Damit geht es dann hoffentlich auch inhaltlich in schnellerem Tempo weiter.
- nächste Schritte: Konstituierung TBk Kerngruppe (Ende Mai/Juni), Konsolidierung Code für "Internal Launch" (OS für Kerngruppe TBk), Roadmap für Entwicklung

**Comment by MarkusTiede** [comment]
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/1764012/235882756-d514ef78-7d64-44e3-99d7-a3074586098e.png">

@Hannes-Ole : ggfs. spannend / ergänzend - heute von der #transform23: https://github.com/RaffiBienz/arborizer

**Comment by MarkusTiede** [comment]
https://www.bfh.ch/en/about-bfh/people/ydixhw6wrghq/

**Comment by Hannes-Ole** [comment]
Quick update: Treffen mit Matthias Kuhn (OpenGIS) gehabt, sind interessiert. Es ist ein Support Vertrag entstanden.

**Comment by MarkusTiede** [comment]
https://www.ost.ch/de/person/stefan-f-keller-1419

**Comment by MarkusTiede** [comment]
Repo: https://github.com/HAFL-WWI/TBk

**Comment by MarkusTiede** [comment]
https://www.opensource.construction

**Comment by Hannes-Ole** [comment]
**Updates:**
- BAFU Projekt Vertrag abgeschlossen für ein Dachprojekt. Damit hat die Weiterentwicklung TBk zu Open Source eine Basisförderung (Laufzeit 3 Jahre, Projektinhalt: Aufbau der Community, Umbau Code, Dokumentation, ...)
- Wald und Holz 4.0 Startanlass (wh40.ch) wurde genutzt, um Arbeitsgruppe zu konstitutieren. Damit wurde der erste Schritt gemacht, die TBk OS Community ins Rollen zu bringen. Es waren kantonale Amtsvertreter, Forstbetriebe, BAFU sowie Ingenieurbüros vertreten.
- Der Supportvertrag mit OpenGIS ist hilfreich und funktioniert gut, um Issues zu lösen, die mit QGIS Core verzahnt sind.
- Das git repository https://github.com/HAFL-WWI/TBk ist aktuell noch **_privat_**, aber nun besser gepflegt und aktiv in Benutzung/Weiterentwicklung. Die Weiterentwicklung geht endlich voran. 
- Zeitrahmen Open Source Veröffentlichung im Laufe 2024

**Besprechung Markus Tiede:**
- Reminder OS Launch Checklist
- Technical Review eventuell durch IPST. Es gibt eine Reihe von Basis-Checks, die zumindest zum Teil automatisiert durchgeführt werden können
- Markus Tiede Zugriff zu TBk repository gewährt

**Comment by Hannes-Ole** [comment]
Am 18. Januar fand ein Workshop im Rahmen des Wald & Holz 4.0 Projektes statt (wh40.ch, eine Digitalisierungsintitiative für die Forstbranche) - wir nutzen hier TBk als Beispiel für den Digitalisierungsprozess und die dort formierte Arbeitsgruppe fungiert als Basis für die Konstituierung der TBk (Open Source) Arbeitsgruppe/Community.

Im Workshop wurde die Arbeitsgruppe TBk strukturiert  in drei Untergruppen (User Community, Power User, Developer) und eine vierte Gruppe, die Kerngruppe, die aus Vertretern dieser Untergruppen besteht.
Es wurde zudem das Open Source Konzept skizziert und für TBk konzipiert, analog zu einem grossartigen Vortrag von Christian Zosel (Adfinis). Die für TBk adaptierten Folien sind hier zu finden: https://nextcloud.bfh.science/index.php/s/5fCLszjjSkaZknp

Im April/Mai wird bei einem nächsten Treffen die Arbeitsgruppe, insbesondere die Kerngruppe, weiter konkret ausgestaltet, insbesondere hinsichtlich Rollenteilung/Verantwortlichkeiten und Kompetenzen. Damit ist ein weiterer Meilenstein erreicht.

Mit dem konkretisieren der Strukturen geht es dann auch voran bzgl. der technischen Open Source Aspekte (Checklist, Technical Review)

**Comment by Hannes-Ole** [comment]
Update:
Am 14.5 fand ein weiterer Workshop im Rahmen des Wald & Holz 4.0 Projektes statt, bei dem über die Rollenverteilung innerhalb der Community gesprochen wurde und das Finanzierungsmodell anhand verwandter Beispiele thematisiert wurde ([Programm und Slides hier](https://nextcloud.bfh.science/index.php/s/8AAF4eN6z5rgTHo) ([FR ici](https://nextcloud.bfh.science/index.php/s/DwNd5ZsTRzz9Mt6) - attention, traduction automatique).

Am 17.7 sollen diese Themen vertieft werden und Grundsatzentscheide bzgl. Lizenz, Finanzierungsmodell und Webauftritt getroffen werden. Ein wichtiger Meilenstein im Bezug auf dieses Issue und den Open Source Werdegang von TBk :)
